/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kritter.adserving.thrift.struct;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Change version whenever there is change in the structure.
 */
public enum InventorySource implements org.apache.thrift.TEnum {
  RTB_EXCHANGE(2),
  DIRECT_PUBLISHER(1),
  SSP(3),
  DCP(4),
  AGGREGATOR(5),
  OPENRTB_AGGREGATOR(6);

  private final int value;

  private InventorySource(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static InventorySource findByValue(int value) { 
    switch (value) {
      case 2:
        return RTB_EXCHANGE;
      case 1:
        return DIRECT_PUBLISHER;
      case 3:
        return SSP;
      case 4:
        return DCP;
      case 5:
        return AGGREGATOR;
      case 6:
        return OPENRTB_AGGREGATOR;
      default:
        return null;
    }
  }
}
