/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kritter.adserving.thrift.struct;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Reason for no fill
 */
public enum NoFillReason implements org.apache.thrift.TEnum {
  FILL(1),
  BIDDER_FLOOR_UNMET(2),
  NO_ADS(3),
  ALPHA_EMPTY(4),
  AD_ABSENT_IN_ALPHA(5),
  BID_ZERO(6),
  PUB_FLOOR_ABSENT(7),
  CAMPAIGN_BID_FLOOR_UNMET(8),
  NO_ADS_COUNTRY_CARRIER(9),
  NO_ADS_BRAND(10),
  NO_ADS_MODEL(11),
  SITE_INC_EXC_ADV(12),
  AD_INV_SRC(13),
  AD_INV_SRC_TYPE(14),
  AD_SITE_CATEGORY_INC_EXC(15),
  SITE_AD_CATEGORY_INC_EXC(16),
  AD_PUB_INC_EXC(17),
  AD_SITE_INC_EXC(18),
  AD_SITE_HYGIENE(19),
  AD_OS_MIDP(20),
  AD_BROWSER(21),
  SITE_AD_DOMAIN(22),
  AD_CUSTOM_IP(23),
  AD_HOUR_DAY(24),
  CREATIVE_ATTR(25),
  CREATIVE_SIZE(26),
  ECPM_FLOOR_UNMET(27),
  SITE_INC_EXC_CAMPAIGNS(28),
  CAMPAIGN_DATE_BUDGET(29),
  BIDDER_BID_NEGATIVE_ZERO(30),
  INTERNAL_ERROR(31),
  AD_ZIPCODE(32),
  AD_LAT_LONG(33),
  AD_EXT_SUPPLY_ATTR(34),
  AD_DIRECT_SUPPLY_INC_EXC(35),
  AD_EXCHNG_SUPPLY_INC_EXC(36),
  SITE_INC_EXC_ADV_CMPGN(37),
  NO_ADS_CONNECTION_TYPE(38),
  NO_ADS_TABLET_TARGETING(39),
  AD_SUPPLY_INC_EXC(40),
  ONLY_MEDIATION_DP(41),
  ONLY_DSP_DP(42),
  EX_OD_REQ_CONVERT(43),
  EX_OD_REQ_SER_NULL(44),
  EX_OD_URL_MAP_EMP(45),
  EX_OD_EXEC_NULL(46),
  EX_OD_API_INCORRECT(47),
  EX_OD_RESP_EMPTY(48),
  EX_OD_BID_RESP_EMPTY(49),
  EX_OD_AP_INCORRECT(50),
  EX_OD_WIN_NULL(51),
  EX_OD_EXCEPTION(52),
  ONLY_DIRECT_DP(53),
  ONLY_DIRECTthenMed_DP(54),
  ONLY_DIRECTthenDSP_DP(55),
  NATIVE_MISMATCH(56),
  VIDEO_MISMATCH(57),
  Video_ApiFramework(58),
  Video_Mime(59),
  Video_Duration(60),
  Video_Protocol(61),
  Video_StartDelay(62),
  Video_Width(63),
  Video_Height(64),
  Video_Linearity(65),
  Video_MaxExtended(66),
  Video_BitRate(67),
  Video_Boxing(68),
  Video_PlayBack(69),
  Video_Delivery(70),
  Video_CompanionType(71),
  Video_Exception(72),
  CREATIVE_NOT_VIDEO(73),
  DEAL_ID_MISMATCH(74),
  VIDEO_PROPS_NULL(75),
  NATIVE_REQ_NULL(76),
  NATIVE_PROPS_NULL(77),
  NATIVE_REQ_ASSET_NULL(78),
  CREATIVE_NOT_NATIVE(79),
  NATIVE_TITLE_LEN(80),
  NATIVE_IMGSIZE(81),
  NATIVE_DESC_LEN(82),
  DEVICE_TYPE(83),
  FREQUENCY_CAP(84),
  CREATIVE_FORMAT_ERROR(85),
  NO_ADS_COUNTRY_CARRIER_OS_BRAND(86),
  CAMPAIGN_NOT_FOUND(87),
  RETARGETING(88),
  LOST_TO_COMPETITION(89),
  NO_ADS_STATE(90),
  NO_ADS_CITY(91),
  MMA_MISMATCH(92),
  MMA_IND_FILTER(93),
  MMA_CAT_TARGET(94),
  ADPOSITION_MISMATCH(95),
  CHANNEL_MISMATCH(96),
  VIDEO_DEMAND_PROPS_NF(97),
  VIDEO_SUPPLY_PROPS_NF(98),
  USER_ID_INC_EXC_FILTER(99),
  SSL_TRAFFIC_FILTER(100),
  USER_ID_ABSENT(101),
  BLKBYCOSTPERDAILY(102),
  AUDIENCE_TARGETING_FAILED(103),
  ADVINFOMISMATCH(104),
  EXTSITEIDFILE(105),
  CTR_GOAL_UNMET(106),
  AD_DAY_WEEK(107),
  NATIVE_VIDEO_MISMATCH(108),
  EXCHANGE_DATA_AUDIENCE(109),
  EXCHANGE_SSP_MISMATCH(110),
  DOMAIN_MISMATCH(111),
  CAMPAIGN_PACING(112),
  PASSED_BACK(113);

  private final int value;

  private NoFillReason(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NoFillReason findByValue(int value) { 
    switch (value) {
      case 1:
        return FILL;
      case 2:
        return BIDDER_FLOOR_UNMET;
      case 3:
        return NO_ADS;
      case 4:
        return ALPHA_EMPTY;
      case 5:
        return AD_ABSENT_IN_ALPHA;
      case 6:
        return BID_ZERO;
      case 7:
        return PUB_FLOOR_ABSENT;
      case 8:
        return CAMPAIGN_BID_FLOOR_UNMET;
      case 9:
        return NO_ADS_COUNTRY_CARRIER;
      case 10:
        return NO_ADS_BRAND;
      case 11:
        return NO_ADS_MODEL;
      case 12:
        return SITE_INC_EXC_ADV;
      case 13:
        return AD_INV_SRC;
      case 14:
        return AD_INV_SRC_TYPE;
      case 15:
        return AD_SITE_CATEGORY_INC_EXC;
      case 16:
        return SITE_AD_CATEGORY_INC_EXC;
      case 17:
        return AD_PUB_INC_EXC;
      case 18:
        return AD_SITE_INC_EXC;
      case 19:
        return AD_SITE_HYGIENE;
      case 20:
        return AD_OS_MIDP;
      case 21:
        return AD_BROWSER;
      case 22:
        return SITE_AD_DOMAIN;
      case 23:
        return AD_CUSTOM_IP;
      case 24:
        return AD_HOUR_DAY;
      case 25:
        return CREATIVE_ATTR;
      case 26:
        return CREATIVE_SIZE;
      case 27:
        return ECPM_FLOOR_UNMET;
      case 28:
        return SITE_INC_EXC_CAMPAIGNS;
      case 29:
        return CAMPAIGN_DATE_BUDGET;
      case 30:
        return BIDDER_BID_NEGATIVE_ZERO;
      case 31:
        return INTERNAL_ERROR;
      case 32:
        return AD_ZIPCODE;
      case 33:
        return AD_LAT_LONG;
      case 34:
        return AD_EXT_SUPPLY_ATTR;
      case 35:
        return AD_DIRECT_SUPPLY_INC_EXC;
      case 36:
        return AD_EXCHNG_SUPPLY_INC_EXC;
      case 37:
        return SITE_INC_EXC_ADV_CMPGN;
      case 38:
        return NO_ADS_CONNECTION_TYPE;
      case 39:
        return NO_ADS_TABLET_TARGETING;
      case 40:
        return AD_SUPPLY_INC_EXC;
      case 41:
        return ONLY_MEDIATION_DP;
      case 42:
        return ONLY_DSP_DP;
      case 43:
        return EX_OD_REQ_CONVERT;
      case 44:
        return EX_OD_REQ_SER_NULL;
      case 45:
        return EX_OD_URL_MAP_EMP;
      case 46:
        return EX_OD_EXEC_NULL;
      case 47:
        return EX_OD_API_INCORRECT;
      case 48:
        return EX_OD_RESP_EMPTY;
      case 49:
        return EX_OD_BID_RESP_EMPTY;
      case 50:
        return EX_OD_AP_INCORRECT;
      case 51:
        return EX_OD_WIN_NULL;
      case 52:
        return EX_OD_EXCEPTION;
      case 53:
        return ONLY_DIRECT_DP;
      case 54:
        return ONLY_DIRECTthenMed_DP;
      case 55:
        return ONLY_DIRECTthenDSP_DP;
      case 56:
        return NATIVE_MISMATCH;
      case 57:
        return VIDEO_MISMATCH;
      case 58:
        return Video_ApiFramework;
      case 59:
        return Video_Mime;
      case 60:
        return Video_Duration;
      case 61:
        return Video_Protocol;
      case 62:
        return Video_StartDelay;
      case 63:
        return Video_Width;
      case 64:
        return Video_Height;
      case 65:
        return Video_Linearity;
      case 66:
        return Video_MaxExtended;
      case 67:
        return Video_BitRate;
      case 68:
        return Video_Boxing;
      case 69:
        return Video_PlayBack;
      case 70:
        return Video_Delivery;
      case 71:
        return Video_CompanionType;
      case 72:
        return Video_Exception;
      case 73:
        return CREATIVE_NOT_VIDEO;
      case 74:
        return DEAL_ID_MISMATCH;
      case 75:
        return VIDEO_PROPS_NULL;
      case 76:
        return NATIVE_REQ_NULL;
      case 77:
        return NATIVE_PROPS_NULL;
      case 78:
        return NATIVE_REQ_ASSET_NULL;
      case 79:
        return CREATIVE_NOT_NATIVE;
      case 80:
        return NATIVE_TITLE_LEN;
      case 81:
        return NATIVE_IMGSIZE;
      case 82:
        return NATIVE_DESC_LEN;
      case 83:
        return DEVICE_TYPE;
      case 84:
        return FREQUENCY_CAP;
      case 85:
        return CREATIVE_FORMAT_ERROR;
      case 86:
        return NO_ADS_COUNTRY_CARRIER_OS_BRAND;
      case 87:
        return CAMPAIGN_NOT_FOUND;
      case 88:
        return RETARGETING;
      case 89:
        return LOST_TO_COMPETITION;
      case 90:
        return NO_ADS_STATE;
      case 91:
        return NO_ADS_CITY;
      case 92:
        return MMA_MISMATCH;
      case 93:
        return MMA_IND_FILTER;
      case 94:
        return MMA_CAT_TARGET;
      case 95:
        return ADPOSITION_MISMATCH;
      case 96:
        return CHANNEL_MISMATCH;
      case 97:
        return VIDEO_DEMAND_PROPS_NF;
      case 98:
        return VIDEO_SUPPLY_PROPS_NF;
      case 99:
        return USER_ID_INC_EXC_FILTER;
      case 100:
        return SSL_TRAFFIC_FILTER;
      case 101:
        return USER_ID_ABSENT;
      case 102:
        return BLKBYCOSTPERDAILY;
      case 103:
        return AUDIENCE_TARGETING_FAILED;
      case 104:
        return ADVINFOMISMATCH;
      case 105:
        return EXTSITEIDFILE;
      case 106:
        return CTR_GOAL_UNMET;
      case 107:
        return AD_DAY_WEEK;
      case 108:
        return NATIVE_VIDEO_MISMATCH;
      case 109:
        return EXCHANGE_DATA_AUDIENCE;
      case 110:
        return EXCHANGE_SSP_MISMATCH;
      case 111:
        return DOMAIN_MISMATCH;
      case 112:
        return CAMPAIGN_PACING;
      case 113:
        return PASSED_BACK;
      default:
        return null;
    }
  }
}
